"""point_cloud_fields

Revision ID: 6afc560531e4
Revises: a7a1b8429fba
Create Date: 2022-07-10 17:58:42.845054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6afc560531e4'
down_revision = 'a7a1b8429fba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_cloud', sa.Column('point_count', sa.Integer(), nullable=True))
    op.add_column('point_cloud', sa.Column('slurm_state', sa.String(length=255), nullable=True))
    op.drop_column('point_cloud', 'additional')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_cloud', sa.Column('additional', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('point_cloud', 'slurm_state')
    op.drop_column('point_cloud', 'point_count')
    # ### end Alembic commands ###
