"""point_cloud_remove_log

Revision ID: af76ec3bad4b
Revises: 3f7377751ab6
Create Date: 2022-07-12 11:59:58.087320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af76ec3bad4b'
down_revision = '3f7377751ab6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point_cloud', 'log')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_cloud', sa.Column('log', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
